### ISSUE TITLE
Connection pool size

### ISSUE THREAD

**Issue by voidmonk** [marcoCasamento/Hangfire.Redis.StackExchange#20]
Hi Marco,

Is there a Redis connection pool limit defined (and if so, configurable) in this lib? The original Hangfire.Redis lib had a [limit of 50 connections](https://github.com/HangfireIO/Hangfire.Redis/blob/master/Hangfire.Redis/RedisStorageOptions.cs#L25), due to which the Hangfire job server WorkerCount had to be defined accordingly (to keep it under the storage connection pool limit).

Cheers.

**Comment by marcoCasamento** [comment]
Hi Ashutosh,
no, it doesn't. StackExchange.Redis handle concurrency through multiplexing, it uses a single client to Redis that efficiently pipe requests from multiple thread (workers) to a single channel.
One thing that may worth to note, is that as the load to Redis increase, you may have to adjust the syncTimeout accordingly (default is 1") to something greater. It express the maximum allowed time for synchronous operations here you can find more info on configuration: https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Configuration.md
Br,
Marco



----- Messaggio originale -----
Da: "Ashutosh Nilkanth" <notifications@github.com>
Inviato: ‎18/‎02/‎2016 06:27
A: "marcoCasamento/Hangfire.Redis.StackExchange" <Hangfire.Redis.StackExchange@noreply.github.com>
Oggetto: [Hangfire.Redis.StackExchange] Connection pool size (#20)

Hi Marco,
Is there a Redis connection pool limit defined (and if so, configurable) in this lib? The original Hangfire.Redis lib had a limit of 50 connections, due to which the Hangfire job server WorkerCount had to be defined accordingly (to keep it under the storage connection pool limit).
Cheers.

**Comment by voidmonk** [comment]
Thanks, that makes sense. With Hangfire.Redis.StackExchange, is it just a matter of setting syncTimeout before setting Hangfire storage, like this:

    var redisConfigOptions = new ConfigurationOptions { SyncTimeout = 10000 };

    Hangfire.GlobalConfiguration.Configuration.UseStorage<RedisStorage>(new RedisStorage());

**Comment by voidmonk** [comment]
Any idea about where/how to set SyncTimeout, so that it plays with StackExchange.Redis and Hangfire.Redis.StackExchange?

**Comment by marcoCasamento** [comment]
Hi Ashutosh, sure:

var rs = new RedisStorage("myRedisSrv:6379,syncTimeout=5000");
Hangfire.GlobalConfiguration.Configuration.UseStorage(rs);

the string part is the connectionstring and it supports everything
explained here
https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Configuration.md

br,
Marco

Il giorno mer 9 mar 2016 alle ore 07:42 Ashutosh Nilkanth <
notifications@github.com> ha scritto:

**Comment by voidmonk** [comment]
Thanks.
