### ISSUE TITLE
Is this package legal (regarding Hangfire.Pro) ?

### ISSUE THREAD

**Issue by dc-p8** [marcoCasamento/Hangfire.Redis.StackExchange#80]
Is this package legal ?
I know the question may seem stupid, and it probably is. And maybe I shouldn't put it on github but rather on some forum.

The point is, I don't know enough about legality issues and I'd like to be sure before using this package in production.

You all know that Hangfire.Redis has moved to Hangfire.Pro, thus, I'm supposed to pay if I want to use Hangfire with Redis storage, right ?
On the other hand, since this package is under LGPL3, I can just use it without any obligation to Hangfire ?
Is there something in Hangfire's licence which prohibits from using Hangfire plus Redis without paying ?

**Comment by marcoCasamento** [comment]
I really hope it is! I didn't meant to make any crime :-)
The code is based on the original work from Sergey Odinokov, the author of
Hangfire, but has diverged a lot since then. I tried to gave him all of the
credits, and he also kindly contacted me about what to write in the header
of each file. Request that was promptly fulfilled.
I believe it's fully legal to use it, even the actual licensing model has
been agreed with Sergey Odinokov.

On the flip side I fully recommend to go with the commercial version.
You'll help Hangfire future development and you'll get commercial support.
Furthermore, Hangfire Pro is not just Hangfire.Redis, it also contains some
"filters" to create batches and continuations, that really help to shape
your application.

Hope this helps!


Il giorno mer 2 gen 2019, 17:02 dc-p8 <notifications@github.com> ha scritto:
